### ISSUE TITLE
Core dumped: Illegal instruction

### ISSUE THREAD

**Issue by Ritu-Kundu** [lbcb-sci/raven#16]
Hi Robert,

Thanks for another amazing tool. I am trying to run it on a cluster (compiling machine different from the target machine) using conda installation (v0.0.7). It results in a dumped core with error message from the script being "Illegal instruction". Could it be an issue with Cmake activating -march=native?
I will try source installation as well.

**Comment by rvaser** [comment]
Hi Ritu,
probably that is the case. The best bet would be to compile on the target machine.

Best regards,
Robert

**Comment by rahulsidhu** [comment]
Hi Robert,
I tried to compile it on the target machine and the compilation was successful. Yet it resulted in core-dump with Illegal Instruction. GDBing the core-dump has the following bt:

```
#0  0x00000000004596af in thread_pool::ThreadPool::ThreadPool(unsigned int) ()
Cannot access memory at address 0x7fffffffc328
```

Output of the compilations is as follows:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/projects/sungk/guanp/genomes100/data/tools/raven/build
[  5%] Built target edlib_static
[ 48%] Built target zlibstatic
[ 54%] Built target logger
[ 59%] Built target thread_pool
[ 64%] Built target ram
[ 78%] Built target spoa
[ 89%] Built target racon
[100%] Built target raven
Compilation done.
```
The Error message is 
```
Setting warning flags
[raven::] loaded sequences 1743.184905 s
$WD/job_scripts/24545148: line 38: 64493 Illegal instruction     (core dumped) $RAVEN -t $NUMTH --graphical-fragment-assembly $DATASET $READS > $DATASET.raven.fa
```

**Comment by Ritu-Kundu** [comment]
Hi Robert,
I tried to compile it on the target machine and the compilation was successful. Yet it resulted in core-dump with Illegal Instruction. GDBing the core-dump has the following bt:
```
#0  0x00000000004596af in thread_pool::ThreadPool::ThreadPool(unsigned int) ()
Cannot access memory at address 0x7fffffffc328
```
Output of the compilations is as follows:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/projects/sungk/guanp/genomes100/data/tools/raven/build
[  5%] Built target edlib_static
[ 48%] Built target zlibstatic
[ 54%] Built target logger
[ 59%] Built target thread_pool
[ 64%] Built target ram
[ 78%] Built target spoa
[ 89%] Built target racon
[100%] Built target raven
Compilation done.
```
The Error message is
```
Setting warning flags
[raven::] loaded sequences 1743.184905 s
$WD/job_scripts/24545148: line 38: 64493 Illegal instruction     
(core dumped) $RAVEN -t $NUMTH --graphical-fragment-assembly $DATASET $READS > $DATASET.raven.fa
```

**Comment by rvaser** [comment]
Hi Ritu,
can you check which compiler you have on that machine? Also `libstc++` version.

Best regards,
Robert

**Comment by Ritu-Kundu** [comment]
Hi Robert,

Following are the specs on the target machine:

```
gcc version 8.2.0 (GCC) 
```
```
$ /sbin/ldconfig -p | grep libstdc++
libstdc++.so.6 (libc6,x86-64) => /usr/lib64/libstdc++.so.6 
libstdc++.so.6 (libc6) => /usr/lib/libstdc++.so.6 
libstdc++.so.5 (libc6,x86-64) => /usr/lib64/libstdc++.so.5 
libstdc++.so.5 (libc6) => /usr/lib/libstdc++.so.5 
libstdc++-libc6.2-2.so.3 (libc6) => /usr/lib/libstdc++-libc6.2-2.so.3
```
```
$ strings /usr/lib/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1 
GLIBCXX_3.4.2 
GLIBCXX_3.4.3 
GLIBCXX_3.4.4 
GLIBCXX_3.4.5 
GLIBCXX_3.4.6 
GLIBCXX_3.4.7 
GLIBCXX_3.4.8 
GLIBCXX_3.4.9 
GLIBCXX_3.4.10 
GLIBCXX_3.4.11 
GLIBCXX_3.4.12 
GLIBCXX_3.4.13 
GLIBCXX_FORCE_NEW 
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
```
$ ls -l  /usr/lib/libstdc++.so.6
lrwxrwxrwx 1 root root 19 May 14  2016 /usr/lib/libstdc++.so.6 -> libstdc++.so.6.0.13
```

Although my LD_LIBRARY_PATH has been exported to point to locally installed GCC libs:
```
$ echo $LD_LIBRARY_PATH
$HOME/gcc-8.2.0/lib64:$HOME/gcc-8.2.0/lib:... rest of the path...
```
```
$  ls -l $HOME/gcc-8.2.0/lib64 | grep libstdc++
...
... libstdc++.so -> libstdc++.so.6.0.25
...
```

**Comment by rvaser** [comment]
Can you please run `make clean` and `make VERBOSE=1` to see if `cmake` picked up the right compiler?

**Comment by Ritu-Kundu** [comment]
Thanks Robert. I finally got hold of a machine to complete this run. This time everything went smoothly.

**Comment by rvaser** [comment]
I am glad it finally worked :)
